#!/usr/bin/env bash

TERRAFORM_DIR="terraform"
source "${TERRAFORM_DIR}/env.sh"
secret_files=$(find . -name secret.* | grep -v '.enc')

decrypt_file() {
    KEY_NAME=${1}
    PLAINTEXT_FILE=${2}
    gcloud kms decrypt \
    --project=${TF_VAR_gcp_project} \
    --location=${TF_VAR_region}  \
    --keyring=${TF_VAR_secrets_app_key_ring_name} \
    --key=${KEY_NAME} \
    --plaintext-file=${PLAINTEXT_FILE} \
    --ciphertext-file="${PLAINTEXT_FILE}.enc"
}

decrypt() {
    for f in ${secret_files}; do
        decrypt_file ${TF_VAR_tf_secrets_app_key_name} "${f}"
    done
}

encrypt_file() {
    KEY_NAME=${1}
    PLAINTEXT_FILE=${2}
    gcloud kms encrypt \
    --project=${TF_VAR_gcp_project} \
    --location=${TF_VAR_region}  \
    --keyring=${TF_VAR_secrets_app_key_ring_name} \
    --key=${KEY_NAME} \
    --plaintext-file=${PLAINTEXT_FILE} \
    --ciphertext-file="${PLAINTEXT_FILE}.enc"
}

encrypt() {
    for f in ${secret_files}; do
        encrypt_file ${TF_VAR_tf_secrets_app_key_name} "${f}"
    done
}

cmd=${1}
case ${cmd} in
    "decrypt")
        decrypt
        ;;
    "encrypt")
        encrypt
        ;;
    "clean")
        cat ${TERRAFORM_SECRETS_MANIFEST_FP} | xargs rm
        ;;
    *)
        echo 'Usage: secrets [decrypt|encrypt|clean]'
esac
