#!/usr/bin/env bash

K8S_SERVICE_NAME="catalog"
K8S_SERVICE_NAME_UPPER="CATALOG"
K8S_SERVICE_VERSION="snapshot"
K8S_SERVICE_LIMIT_N_REPLICAS=1
K8S_SERVICE_LIMIT_MEM="500M"
K8S_SERVICE_LIMIT_CPU="100m"
