---
apiVersion: v1
kind: Service
metadata:
  name: catalog
  annotations:
      prometheus.io/scrape: 'false'  # get metrics from indiv pods
spec:
  selector:
    app: catalog
  type: ClusterIP
  ports:
    - port: 10100
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      volumes:
        - name: app-catalog-gcp-creds
          secret:
            secretName: app-catalog-gcp-creds
      containers:
      - name: catalog
        image: gcr.io/elixir-core-prod/catalog:snapshot
        args: [
          "start",
          "--storagePostgres",
          "--dbURL", "postgres://$(CATALOG_DBUSER)@127.0.0.1:5432/catalog?sslmode=disable"
        ]
        ports:
          - name: service
            containerPort: 10100
          - name: metrics
            containerPort: 10101
          - name: profiler
            containerPort: 10102
        volumeMounts:
          - name: app-catalog-gcp-creds
            mountPath: /var/secrets/gcp
            readOnly: true
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/gcp/creds.json
          - name: CATALOG_DBUSER
            valueFrom:
              secretKeyRef:
                name: app-catalog-db-creds
                key: user
          - name: CATALOG_DBPASSWORD
            valueFrom:
              secretKeyRef:
                name: app-catalog-db-creds
                key: password
        resources:
          limits:
            memory: 500M
            cpu: 100m
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: [
          "/cloud_sql_proxy",
          "-instances=elixir-deploy-staging-1:us-east1:primary-1=tcp:5432",
          "-credential_file=/var/secrets/gcp/creds.json"
        ]
        volumeMounts:
          - name: app-catalog-gcp-creds
            mountPath: /var/secrets/gcp
            readOnly: true
