---
apiVersion: v1
kind: Service
metadata:
  name: ${K8S_SERVICE_NAME}
  annotations:
      prometheus.io/scrape: 'false'  # get metrics from indiv pods
spec:
  selector:
    app: ${K8S_SERVICE_NAME}
  type: ClusterIP
  ports:
    - port: 10100
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ${K8S_SERVICE_NAME}
spec:
  replicas: ${K8S_SERVICE_LIMIT_N_REPLICAS}
  selector:
    matchLabels:
      app: ${K8S_SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${K8S_SERVICE_NAME}
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      volumes:
        - name: app-${K8S_SERVICE_NAME}-creds
          secret:
            secretName: app-${K8S_SERVICE_NAME}-creds
      containers:
      - name: ${K8S_SERVICE_NAME}
        image: gcr.io/elixir-core-prod/${K8S_SERVICE_NAME}:${K8S_SERVICE_VERSION}
        args: [
          "start",
          ${K8S_SERVICE_START_ARGS}
        ]
        ports:
          - name: service
            containerPort: 10100
          - name: metrics
            containerPort: 10101
          - name: profiler
            containerPort: 10102
        volumeMounts:
          - name: app-${K8S_SERVICE_NAME}-creds
            mountPath: /var/secrets/google
        env:
          - name: GODEBUG         # ensure we use the pure Go (rather than CGO) DNS
            value: netdns=go      # resolver (see https://golang.org/src/net/net.go)
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/creds.json
        resources:
          limits:
            memory: ${K8S_SERVICE_LIMIT_MEM}
            cpu: ${K8S_SERVICE_LIMIT_CPU}
